// <auto-generated />
namespace Vision_V1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Scene_Story : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Scene_Story));
        
        string IMigrationMetadata.Id
        {
            get { return "201801101628035_Scene_Story"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
